CREATE TABLE chargers
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name         TEXT                                               NOT NULL UNIQUE,
    lat          double precision	                                        NOT NULL,
    lon          double precision	                                        NOT NULL,

    date_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE reservations
(
    user_id    TEXT                                           NOT NULL,
    charger_id INT REFERENCES chargers (id) ON DELETE CASCADE NOT NULL,
    time_from  TIMESTAMP WITH TIME ZONE                       NOT NULL,
    time_until TIMESTAMP WITH TIME ZONE                       NOT NULL
);